import { Link } from "react-router-dom";

export function HomePage() {
  return <section className="home-view">
    <div className="home-hero"><div><span className="eyebrow">De colega para colega</span><h1>Programação começa<br />um passo de cada vez.</h1><p>Um projeto criado por Guilherme para ajudar a turma na primeira etapa de Fundamentos de Programação. Aprenda lógica usando C, entenda os símbolos e pratique com explicações para cada passo.</p><div className="actions"><Link className="action" to="/aulas/">Começar pelas aulas →</Link><Link className="secondary" to="/laboratorio/">Abrir laboratório C</Link></div><p className="home-footnote">Nunca programou ou ainda está se acostumando com o computador? Comece pelas primeiras aulas. Você não precisa chegar sabendo.</p></div><div className="home-code"><div className="code-toolbar"><span>Seu primeiro programa</span><span>C</span></div><pre>#include &lt;stdio.h&gt;{"\n\n"}int main(void) {'{'}{"\n"}    printf("Ola, turma!\\n");{"\n"}    return 0;{"\n"}{'}'}</pre><div className="home-code-note"><strong>{'{ }'}</strong><p>Estas chaves marcam o começo e o fim de um bloco. Cada detalhe tem uma explicação nas aulas.</p></div></div></div>
    <aside className="teacher-note"><span className="eyebrow">Apoio às aulas</span><h2>Ficou com dúvida? Consulte o professor.</h2><p>O site é uma iniciativa de um colega para apoiar seus estudos. As aulas e as orientações do professor <strong>Manfred Heil Junior</strong> continuam sendo sua referência.</p></aside>
    <nav className="home-shortcuts" aria-label="Sobre este projeto"><a href="#como-estudar">Como estudar</a><a href="#sobre-projeto">Objetivo</a><a href="#base-disciplina">Disciplina e materiais</a><a href="#feedback">Enviar feedback</a></nav>
    <section id="como-estudar" className="home-path"><div className="section-heading"><div><span className="eyebrow">Aprenda no seu ritmo</span><h2>Por onde começar?</h2></div></div><div className="home-cards"><Link className="home-card" to="/aulas/"><span className="home-step">01 / ENTENDER</span><h3>Aulas, linha por linha</h3><p>Abra Aulas e comece no nível Básico. Leia a explicação, acompanhe o exemplo e responda às perguntas.</p><span className="home-card-link">Explorar as aulas →</span></Link><Link className="home-card" to="/exercicios/"><span className="home-step">02 / PRATICAR</span><h3>Exercícios com apoio</h3><p>Escolha um tema que já estudou. Tente resolver, use uma dica e compare sua saída com os testes.</p><span className="home-card-link">Escolher um exercício →</span></Link><Link className="home-card" to="/laboratorio/"><span className="home-step">03 / EXPERIMENTAR</span><h3>Seu laboratório de C</h3><p>Escreva ou altere um programa em C, preencha a entrada e observe o resultado.</p><span className="home-card-link">Experimentar agora →</span></Link></div></section>
    <section id="sobre-projeto" className="home-about"><div><span className="eyebrow">Sobre o projeto</span><h2>Entender de verdade, desde o começo.</h2></div><div><p>O Lógica em Prática nasceu de uma dificuldade da turma: quem está começando precisa entender até os detalhes que parecem pequenos, como uma chave, um ponto e vírgula ou uma mensagem de erro.</p><p>A proposta é revisar o conteúdo da disciplina, responder às perguntas e experimentar, um conceito de cada vez.</p><p>Use o site como apoio às aulas e pratique também no ambiente da disciplina.</p></div></section>
    <section id="base-disciplina" className="home-about"><div><span className="eyebrow">Disciplina e materiais</span><h2>De onde vem a nossa trilha?</h2><p>Fundamentos de Programação<br /><strong>Professor Manfred Heil Junior</strong></p></div><div><p>A organização dos temas usa como referência o <cite>Glossário dos Degraus – Fundamentos de Programação</cite>, de Manfred Heil Junior (2026). As explicações e exercícios deste site foram criados para o projeto.</p><ol className="course-steps"><li><strong>Primeiros passos</strong><span>Algoritmos, ambiente e execução.</span></li><li><strong>Degraus 1 e 2</strong><span>Dados, operações e decisões.</span></li><li><strong>Degraus 3 a 5</strong><span>Repetições, coleções e funções.</span></li></ol><div className="material-reference"><span className="eyebrow">Material de referência</span><h3>Glossário dos Degraus</h3><p>Manfred Heil Junior · Fundamentos de Programação · 2026</p><p>Consulte o glossário e os materiais da disciplina. O documento abaixo é disponibilizado com autorização do autor.</p><div className="actions"><a className="action" href="/materiais/glossario-fundamentos-programacao.pdf" target="_blank" rel="noreferrer">Abrir glossário</a><a className="secondary" href="/materiais/glossario-fundamentos-programacao.pdf" download>Baixar PDF</a></div></div></div></section>
    <section id="feedback" className="home-feedback"><div><span className="eyebrow">Construído com a turma</span><h2>Sua dificuldade ajuda a melhorar o site.</h2><p>Encontrou um erro, uma palavra sem explicação ou um exercício confuso? Conte para o criador do projeto.</p><p><strong>Guilherme · criador do projeto</strong><br />WhatsApp: (47) 99649-5794</p><a className="action" href="https://wa.me/5547996495794?text=Oi%2C%20Guilherme!%20Tenho%20um%20feedback%20sobre%20o%20L%C3%B3gica%20em%20Pr%C3%A1tica." target="_blank" rel="noreferrer">Enviar feedback pelo WhatsApp</a></div><div className="feedback-guide"><h3>O que contar no feedback?</h3><ul><li>Qual aula ou exercício você estava fazendo.</li><li>Onde ficou com dúvida.</li><li>O que esperava e o que apareceu.</li></ul></div></section>
  </section>;
}
