import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { lessons } from "../../content/lessons.js";
import { degrauNames } from "../../content/course.js";
import { completeLesson, getCompletedLessons } from "../../services/session-state.js";

const symbols = { "{ }": "Chaves delimitam um bloco de instruções.", "( )": "Parênteses envolvem condições, argumentos e parâmetros.", ";": "Ponto e vírgula encerra uma instrução.", '" "': "Aspas duplas delimitam texto.", "' '": "Aspas simples delimitam um caractere.", "=": "Um igual atribui um valor.", "==": "Dois iguais comparam valores.", "\\n": "Barra invertida e n representam uma nova linha.", "&": "Em &idade, obtém o endereço da variável para scanf.", "[ ]": "Colchetes declaram ou acessam posições de um vetor.", "//": "Duas barras iniciam um comentário." };
const levels = ["Básico", "Intermediário", "Avançado"];

export function LessonsPage() {
  const [params, setParams] = useSearchParams();
  const activeLesson = lessons.find((item) => item.id === params.get("aula")) || lessons[0];
  const [level, setLevel] = useState(activeLesson.level);
  const [stage, setStage] = useState(0);
  const [line, setLine] = useState(activeLesson.focus);
  const [quizIndex, setQuizIndex] = useState(0);
  const [selected, setSelected] = useState(null);
  const [checked, setChecked] = useState(false);
  const [, refreshProgress] = useState(0);
  useEffect(() => { setLevel(activeLesson.level); setStage(0); setLine(activeLesson.focus); setQuizIndex(0); setSelected(null); setChecked(false); }, [activeLesson.id]);
  const visible = lessons.filter((item) => item.level === level);
  const question = activeLesson.questions[quizIndex];
  const completed = getCompletedLessons();
  const choose = (id) => setParams({ aula: id });
  const finishQuestion = () => { if (quizIndex < activeLesson.questions.length - 1) { setQuizIndex((value) => value + 1); setSelected(null); setChecked(false); } else { completeLesson(activeLesson.id); refreshProgress((value) => value + 1); } };
  return <div className="workspace"><aside className="sidebar"><h2>Seu caminho</h2><div className="levels">{levels.map((item) => <button className={`level ${level === item ? "active" : ""}`} aria-pressed={level === item} key={item} onClick={() => setLevel(item)}>{item}</button>)}</div><p className="level-help">{level === "Básico" ? "Primeiros cliques e degrau 1: dados, contas, entrada e saída." : level === "Intermediário" ? "Degraus 2 e 3: decisões e repetições." : "Degraus 4 e 5: vetores, matrizes e funções."}</p><div className="lesson-list">{visible.map((item, index) => <button className={`lesson-link ${item.id === activeLesson.id ? "active" : ""}`} aria-current={item.id === activeLesson.id ? "page" : undefined} key={item.id} onClick={() => choose(item.id)}><span className="number">{completed.has(item.id) ? "✓" : String(index + 1).padStart(2, "0")}</span><span><strong>{item.title}</strong><small>{item.time}{completed.has(item.id) ? " · concluída" : ""}</small></span></button>)}</div><div className="progress-area">{completed.size} de {lessons.length} aulas concluídas<progress max={lessons.length} value={completed.size} /><small>Progresso desta visita.</small></div></aside><article className="lesson"><div className="lesson-meta"><span className="pill">{activeLesson.level}</span><span>{activeLesson.time} · no seu ritmo</span><span>{degrauNames[activeLesson.degrau]}</span></div><h2>{activeLesson.title}</h2><p className="goal">{activeLesson.goal}</p><nav className="stages" aria-label="Etapas da aula">{["Entender", "Explorar", "Praticar"].map((title, index) => <button className={`stage ${stage === index ? "active" : ""}`} aria-current={stage === index ? "step" : undefined} key={title} onClick={() => setStage(index)}>{index + 1}. {title}</button>)}</nav>{stage === 0 && <Learn lesson={activeLesson} onNext={() => setStage(1)} />}{stage === 1 && <Explore lesson={activeLesson} line={line} setLine={setLine} onNext={() => setStage(2)} onBack={() => setStage(0)} />}{stage === 2 && <Practice lesson={activeLesson} question={question} index={quizIndex} selected={selected} setSelected={setSelected} checked={checked} setChecked={setChecked} onNext={finishQuestion} onBack={() => setStage(1)} />}</article></div>;
}

function Learn({ lesson, onNext }) { return <div id="content"><p className="lead">{lesson.intro}</p>{lesson.paragraphs.map(([title, text]) => <section className="learn-block" key={title}><h3>{title}</h3><p>{text}</p></section>)}<div className="callout"><strong>Guarde esta ideia:</strong> {lesson.tip}</div><button className="action" onClick={onNext}>Explorar o exemplo →</button></div>; }
function Explore({ lesson, line, setLine, onNext, onBack }) { const lines = lesson.code.split("\n"); const [symbol, setSymbol] = useState("{ }"); const description = lesson.notes?.[line] || (lines[line]?.trim() === "" ? "Linha em branco: ajuda a separar partes do código visualmente." : "Esta linha faz parte do exemplo. Observe o bloco em que ela aparece."); return <div id="content"><p>Toque ou clique em uma linha para entender o que ela faz.</p><div className="code-box"><div className="code-toolbar"><span>exemplo.c · programa completo</span><button onClick={() => navigator.clipboard?.writeText(lesson.code)}>Copiar código</button></div><div className="code-scroll">{lines.map((text, index) => <button className={`code-line ${line === index ? "selected" : ""}`} aria-pressed={line === index} aria-label={`Linha ${index + 1}: ${text || "linha em branco"}`} key={`${index}-${text}`} onClick={() => setLine(index)}><span className="line-no">{index + 1}</span><span>{text || " "}</span></button>)}</div></div><div className="line-note" role="status"><strong>Linha {line + 1}, sem mistério</strong>{description}</div><details className="symbol-guide"><summary>Não entendi um símbolo</summary><div className="symbols">{Object.keys(symbols).map((item) => <button className="symbol" aria-pressed={symbol === item} key={item} onClick={() => setSymbol(item)}>{item}</button>)}</div><div className="symbol-description" role="status">{symbols[symbol]}</div></details><div className="actions"><button className="secondary" onClick={onBack}>← Reler a explicação</button><button className="action" onClick={onNext}>Agora, praticar →</button><Link className="secondary" to={`/laboratorio/?codigo=${encodeURIComponent(lesson.code)}`}>Editar e executar este C</Link></div></div>; }
function Practice({ lesson, question, index, selected, setSelected, checked, setChecked, onNext, onBack }) { const correct = checked && selected === question.answer; return <div id="content"><p className="question-count">PERGUNTA {index + 1} DE {lesson.questions.length}</p><h3>{question.question}</h3><div className="options">{question.options.map((option, optionIndex) => <button className={`option ${selected === optionIndex ? "selected" : ""} ${checked && optionIndex === question.answer ? "correct" : ""} ${checked && selected === optionIndex && selected !== question.answer ? "wrong" : ""}`} disabled={checked} key={option} onClick={() => setSelected(optionIndex)}><span className="option-letter">{String.fromCharCode(65 + optionIndex)}</span>{option}</button>)}</div>{checked && <div className={`feedback ${correct ? "good" : "bad"}`} role="status"><strong>{correct ? "Muito bem." : "Vamos revisar."}</strong><p>{question.explanations[selected ?? 0]}</p></div>}{!checked && <button className="text-button" onClick={() => window.alert(question.hint)}>Preciso de uma dica</button>}<div className="actions"><button className="secondary" onClick={onBack}>← Explorar novamente</button><button className="action" disabled={selected === null} onClick={() => checked ? onNext() : setChecked(true)}>{checked ? (index === lesson.questions.length - 1 ? "Concluir aula" : "Próxima pergunta →") : "Conferir resposta"}</button></div></div>; }
